version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8085:80"

  php:
    build: docker/php
    depends_on:
      - db
    volumes:
      - .:/srv/api:rw
      - ./docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      - ./var:/srv/api/var:rw

  nginx:
    build: docker/nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sortie_symfony
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql:rw

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
  es-data:
###< doctrine/doctrine-bundle ###
